[id]
name = hyperloop_data
version = 1.0.0

[install]
is_configured = false
build = 1

[package]
id = hyperloop_data
check_for_updates = false

[ui]
is_visible = true
label = Hyperloop Data

[launcher]
author = Delft Hyperloop
description = Schema-driven telemetry data dashboard for the DH-X prototype pod.
version = 1.0.0
