[id]
name = hyperloop_dynamics
version = 1.0.0

[install]
is_configured = false
build = 1

[package]
id = hyperloop_dynamics
check_for_updates = false

[ui]
is_visible = true
label = Hyperloop Dynamics

[launcher]
author = Delft Hyperloop
description = Real-time telemetry monitor for the DH-X prototype pod.
version = 1.0.0
