[hyperloop_dynamics]
label = Hyperloop Dynamics
description = Monitor pod dynamics, sensors, and battery in real time.
default_height = 800
allow_user_selection = true
disabled = 0
search_fragment = | eval vfl=..., position=..., hv_soc=...
