[id]
name = hyperloop_endurance
version = 1.0.0

[install]
is_configured = false
build = 1

[package]
id = hyperloop_endurance
check_for_updates = false

[ui]
is_visible = true
label = Hyperloop Endurance

[launcher]
author = Delft Hyperloop
description = Endurance telemetry monitor for the DH-X prototype pod.
version = 1.0.0
