[id]
name = hyperloop_analysis
version = 1.0.5

[install]
is_configured = false
build = 6

[package]
id = hyperloop_analysis
check_for_updates = false

[ui]
is_visible = true
label = Hyperloop Analysis

[launcher]
author = Delft Hyperloop
description = Run-analysis workbench for the DH-X prototype pod telemetry.
version = 1.0.5
