[Donut Chart - Demo]
search = index=_internal | stats count by sourcetype | rename sourcetype as label, count as value
dispatch.earliest_time = -1h
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = donut_chart.donut_chart
display.visualizations.custom.donut_chart.donut_chart.colorScheme = splunk
display.visualizations.custom.donut_chart.donut_chart.innerRadius = medium
display.visualizations.custom.donut_chart.donut_chart.showGlow = true
display.visualizations.custom.donut_chart.donut_chart.showLegend = true
display.visualizations.custom.donut_chart.donut_chart.centerLabel =
